#!/bin/bash

# Create and checkout new branch
git checkout -b feat/frontend

# Array of frontend-focused commit messages
commits=(
  "feat: Add move history component"
  "feat: Implement move notation display"
  "feat: Add captured pieces display"
  "feat: Create timer component"
  "feat: Implement game clock"
  "feat: Add time control options"
  "style: Improve board contrast"
  "style: Add piece shadows"
  "style: Enhance button styles"
  "feat: Add sound effects"
  "feat: Implement move sound"
  "feat: Add capture sound"
  "feat: Add check sound"
  "feat: Add game end sound"
  "feat: Create settings panel"
  "feat: Add sound toggle"
  "feat: Add theme selector"
  "feat: Implement light theme"
  "feat: Add board flip option"
  "feat: Create game list component"
  "feat: Add active games display"
  "feat: Implement game filtering"
  "feat: Add search functionality"
  "feat: Create player profile card"
  "feat: Add player stats"
  "feat: Implement rating display"
  "feat: Add avatar component"
  "feat: Create notification system"
  "feat: Add move notifications"
  "feat: Implement game invites"
  "feat: Add friend requests"
  "refactor: Extract board logic"
  "refactor: Optimize piece rendering"
  "refactor: Improve state management"
  "refactor: Clean up component structure"
  "test: Add ChessBoard tests"
  "test: Add WalletConnect tests"
  "test: Add GameControls tests"
  "test: Add integration tests"
  "fix: Board rendering on mobile"
  "fix: Wallet connection timeout"
  "fix: Move validation edge case"
  "fix: Game state sync issue"
  "perf: Optimize re-renders"
  "perf: Add memoization"
  "perf: Lazy load components"
  "perf: Optimize bundle size"
  "feat: Add move animation"
  "feat: Implement piece dragging"
  "feat: Add drag preview"
  "feat: Create drop zones"
  "style: Add hover animations"
  "style: Improve transitions"
  "style: Add loading states"
  "style: Enhance error messages"
  "feat: Add game export"
  "feat: Implement PGN export"
  "feat: Add game import"
  "feat: Create share button"
  "feat: Add copy game link"
  "feat: Implement QR code"
  "feat: Add game replay"
  "feat: Create replay controls"
  "feat: Add step forward/back"
  "feat: Implement auto-replay"
  "feat: Add analysis mode"
  "feat: Create position editor"
  "feat: Add FEN input"
  "feat: Implement board setup"
  "docs: Add component documentation"
  "docs: Update API reference"
  "docs: Add usage examples"
  "docs: Create troubleshooting guide"
  "feat: Add keyboard shortcuts"
  "feat: Implement arrow key navigation"
  "feat: Add hotkey hints"
  "feat: Create help modal"
  "feat: Add tutorial mode"
  "feat: Implement onboarding"
  "feat: Add tooltips"
  "feat: Create FAQ section"
  "style: Improve accessibility"
  "style: Add focus indicators"
  "style: Enhance color contrast"
  "style: Add screen reader text"
  "feat: Add language support"
  "feat: Implement i18n"
  "feat: Add Spanish translation"
  "feat: Add French translation"
  "feat: Create language selector"
  "feat: Add game chat"
  "feat: Implement message input"
  "feat: Add emoji picker"
  "feat: Create chat history"
  "feat: Add message timestamps"
  "feat: Implement read receipts"
  "feat: Add typing indicator"
  "feat: Create user presence"
  "feat: Add online status"
  "feat: Implement last seen"
  "chore: Update dependencies"
  "chore: Fix security vulnerabilities"
  "chore: Update Next.js"
  "chore: Update Tailwind"
)

# Create commits
for i in "${!commits[@]}"; do
  git commit --allow-empty -m "${commits[$i]}"
  echo "Created commit $((i+1))/${#commits[@]}: ${commits[$i]}"
done

echo ""
echo "✅ All 100 commits created on feat/frontend branch!"
echo ""
echo "Total commits on this branch: $(git log --oneline main..feat/frontend | wc -l)"
